apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-frontend
spec:
  selector:
    matchLabels:
      app: crud-frontend
  template:
    metadata:
      labels:
        app: crud-frontend
    spec:
      containers:
      - name: myappcrud-frontend
        image: ravi0520/crud-react-minikube:v5
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: crud-frontend
spec:
  type: NodePort 
  selector:
    app: crud-frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31058 
