apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-backend
spec:
  selector:
    matchLabels:
      app: crud-backend
  template:
    metadata:
      labels:
        app: crud-backend
    spec:
      containers:
      - name: crud-backend
        image: ravi0520/crud-backend:v1
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: crud-backend
spec:
  type: NodePort
  selector:
    app: crud-backend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31887

